#! /bin/sh

bspc config border_width        1
bspc config window_gap         	5

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config focus_by_distance   true

bspc monitor -d I II III IV V

##

bspc rule -a Firefox desktop=^3
bspc rule -a deluge desktop=^5
bspc rule -a thunderbird desktop=^5
bspc rule -a transmission-gtk desktop=^5
bspc rule -a tilda floating=on
bspc rule -a uget-gtk desktop=^4
bspc rule -a eog floating=on
bspc rule -a xfce4-notes floating=on
bspc rule -a xfce4-appfinder floating=on
bspc rule -a orage floating=on
bspc rule -a Pidgin floating=on

bspc config top_padding 25
#bspc config bottom_padding 5
bspc config focus_follows_pointer true
bspc config active_border_color \#ff0000
bspc config focused_border_color \#909090
bspc config normal_border_color \#000000

bspc config urgent_border_color \#ff0000

tilda & ###########

eval $(cat ~/.fehbg)
exec indicator-multiload &
xset +fp /home/subhrajit/.fonts &
compton --config /home/subhrajit/.compton.conf &
nm-applet &
thunar --daemon &
xflux -l 21 -o 82.5 &
#xfce4-notes &
tint2 &
sleep 5s; notify-send "Welcome Subhrajit"
python3 /home/subhrajit/scripts/download.py
